### ISSUE TITLE
 /play Command Not Working for Audio Files in Telegram Chat

### ISSUE THREAD

**Issue by appmahina** [TheTeamVivek/YukkiMusic#11]
When attempting to play an audio file in the Telegram chat using the /play command, the file does not play as expected. Instead, an error is generated and logged. Below is the error log captured during the attempt:

`ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
...
Option loop not found.
Error opening input file /Users/gabrielmaia/Documents/my/YukkiMusic/downloads/AgADzicAAoXasEg.mp3.
Error opening input files: Option not found
...
list index out of range
27-Oct-24 15:37:34 - ERROR - root - play_commnd - 121 - list index out of range
27-Oct-24 15:37:34 - ERROR - YukkiMusic.plugins.play.play - play_commnd - 127 - IndexError list index out of range`

**Steps to Reproduce:**

1. Use the /play command in a Telegram chat with an audio file.
2. Observe that the audio file does not play.
3. Check the logs for errors.

**Expected Behavior:**
The audio file should start playing when the /play command is issued.

Actual Behavior:
The audio file is not played, and the bot generates an error, specifically "list index out of range".

**Environment Details:**

- FFmpeg version: 7.1
- Platform: macOS, built with Apple clang version 16.0.0

**Additional Information:**
The error seems related to an incorrect option or parameter passed to FFmpeg, as indicated by "Option loop not found" and "Error opening input files: Option not found". Additionally, the "list index out of range" error suggests an issue in the code related to handling the audio file list.

Thank you in advance for the support!

**Comment by Vivekkumar-IN** [comment]
In [commit](https://github.com/TheTeamVivek/YukkiMusic/commit/8163aeae0f7b745db89968972df0d64261fbf0c7), I added `exc_info=True` to the logging setup to capture the full traceback for errors. Please update your bot to this latest commit and try the `/play` command again. If an error still occurs, kindly share the full error log for further analysis and drop the audio file in the @TheTeamVk on Telegram.

**Comment by gabrielmaialva33** [comment]
Hello @Vivekkumar-IN, thank you for your suggestion to add exc_info=True to capture the full traceback. 

`
➜  python3.11 -m YukkiMusic
[28-Oct-24 08:44:21 - INFO] - root - Directories Updated.
[28-Oct-24 08:44:21 - INFO] - YukkiMusic.core.git - Git Client Found [VPS DEPLOYER]
[28-Oct-24 08:44:22 - INFO] - YukkiMusic.core.git - Fetched Updates from: https://github.com/TheTeamVivek/YukkiMusic
[28-Oct-24 08:44:22 - INFO] - YukkiMusic.misc - Database Initialized.
[28-Oct-24 08:44:22 - INFO] - YukkiMusic.misc - Sudoers Loaded.
[28-Oct-24 08:44:22 - INFO] - YukkiMusic.core.bot - Starting Bot
[28-Oct-24 08:44:31 - INFO] - YukkiMusic.core.bot - MusicBot started as Mahina
[28-Oct-24 08:44:31 - INFO] - YukkiMusic.plugins - Successfully Imported All Modules 
[28-Oct-24 08:44:31 - INFO] - YukkiMusic.core.userbot - Starting Assistant Clients
[28-Oct-24 08:44:33 - INFO] - YukkiMusic.core.call - Starting PyTgCall Clients
PyTgCalls v2.0.4 powered by NTgCalls v1.2.3, Copyright (C) 2021-2024 Laky-64 <https://github.com/Laky-64>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

[28-Oct-24 08:44:34 - INFO] - YukkiMusic - Assistant Started Sucessfully
[28-Oct-24 08:44:37 - INFO] - YukkiMusic - YukkiMusic Started Successfully
[28-Oct-24 08:45:43 - ERROR] - YukkiMusic.plugins.play.play - An error occurred
Traceback (most recent call last):
  File "/Users/gabrielmaia/Documents/my/YukkiMusic/YukkiMusic/plugins/play/play.py", line 108, in play_commnd
    await stream(
  File "/Users/gabrielmaia/Documents/my/YukkiMusic/YukkiMusic/utils/stream/stream.py", line 453, in stream
    db[chat_id][0]["mystic"] = run
    ~~~~~~~~~~~^^^
IndexError: list index out of range
`

After implementing this and adjusting logging.py to DEBUG mode with the following setup:

`
...
Option loop not found.
Error opening input file /Users/mahina/Documents/my/YukkiMusic/downloads/AgADzicAAoXasEg.mp3.
Error opening input files: Option not found
...
`

I noticed that the ffmpeg error persists, specifically the Option loop not found issue. Additionally, the file path in the log includes an unexpected period (".") where it doesn't exist in the actual path, which might contribute to the issue but doesn’t completely resolve it.

The "list index out of range" error suggests a deeper, possibly internal issue within the py-tgcalls library, which appears to be mishandling the audio file list.

I also examined the traceback in play.py:

```
Traceback (most recent call last):
  File "/Users/gabrielmaia/Documents/my/YukkiMusic/YukkiMusic/plugins/play/play.py", line 108, in play_commnd
    await stream(
  File "/Users/gabrielmaia/Documents/my/YukkiMusic/YukkiMusic/utils/stream/stream.py", line 453, in stream
    db[chat_id][0]["mystic"] = run
    ~~~~~~~~~~~^^^
```

Even after addressing the file path, the issue persists, which suggests a possible root cause in the py-tgcalls dependency itself.

**Comment by Vivekkumar-IN** [comment]
@gabrielmaialva33 Can you drop your file that you are trying to play at @Vivekkumar_in on telagram

**Comment by Vivekkumar0708** [comment]
If there are no issue should i close this Issue?

**Comment by Vivekkumar-IN** [comment]
If there are no persistent issues, I am closing this issue.
